kind: Namespace
apiVersion: v1
metadata:
  name: prod
---
kind: Namespace
apiVersion: v1
metadata:
  name: dev
---
kind: Namespace
apiVersion: v1
metadata:
  name: staging1
---
kind: Namespace
apiVersion: v1
metadata:
  name: staging2
---
kind: Namespace
apiVersion: v1
metadata:
  name: staging3
---
kind: Namespace
apiVersion: v1
metadata:
  name: staging4
